version: "3.8"
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8443:80
    volumes:
      - C:/Users/Dan Porter/Sites/mdjm-plugin/wp-content/plugins/mobile-dj-manager/:/var/www/html/wp-content/plugins/mobile-dj-manager/
      - C:/Users/Dan Porter/Sites/mdjm-plugin/wp-content/:/var/www/html/wp-content
      - C:/Users/Dan Porter/Sites/mdjm-plugin/wp-config.php:/var/www/html/wp-config.php
    environment:
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mdjm_plugin
      WORDPRESS_DB_HOST: db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mdjm_plugin
    volumes:
      - db_data:/var/lib/mysql
      - C:/Users/Dan Porter/Sites/mdjm-plugin/mdjm_plugin_base.sql:/docker-entrypoint-initdb.d/mdjm_plugin_base.sql
    command: ["--default-authentication-plugin=mysql_native_password"]
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp-pass
      MYSQL_ROOT_PASSWORD: rootPassword
    ports:
      - 3001:80
volumes:
  db_data: