name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
      - '!*-alpha*'
      - '!*-beta*'
      - '!*-rc*'
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: mobile-dj-manager
